# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: XyGod
subtitle: ''
description: ''
keywords: ''
author: Qu Hou
language:
  - en
  - zh-CN
permalink: /:title/
timezone: ''
github_repo: https://github.com/xygodcyx/hexo-blog

langselect:
  enable: true # If open, it will automatically generation lang-select button.This button can jump in articles in different languages, but the articles must have the same name.
  options: # langselect button display options
    en: English
    zh-CN: 简体中文
    # tw: 正體中文

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://quhou.top
root: /
# permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

debug: true
logger: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
# highlight:
#   enable: false # 是否启用代码高亮
#   line_number: true # 显示行号
#   auto_detect: true # 自动检测语言
#   # tab_replace: ''  # 替换Tab为空格

# prism_plugin:
#   mode: 'preprocess' # 预处理模式
#   theme: 'vs' # 主题名
#   line_number: true # 显示行号
#   custom_css: false # 禁用默认CSS（主题自带样式时用）

syntax_highlight:
  enable: false
  theme: 'atom-one-dark' # 可选主题：github, solarized-light, etc
  line_number: true

prismjs:
  enable: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
# ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: adagio

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

server:
  compress: true # 开启压缩

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
  plugins:
    - markdown-it-container
    # 你还可以加其他插件，例如：
    # - markdown-it-task-lists
    # - markdown-it-footnote
    # - markdown-it-emoji


marked:
  escape: false

search:
  path: search.json
  field: post
  format: striptags
  limit: 10000

deploy:
  type: git
  repo: git@github.com:xygodcyx/blog.git
  branch: deploy